name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths-ignore:
      - "docs/**"
      - "README.md"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - uses: Swatinem/rust-cache@v1
      - name: "Install Dependencies"
        run: make install-deps
      - name: "Install Rust Wasm targets"
        run: |
          rustup target add wasm32-wasi
          rustup target add wasm32-unknown-unknown
      - name: "Run clippy and fmt"
        run: make improve        
      - name: "Build SpiderLightning and Slight"
        run: make build
      - name: "Build Rust Examples"
        run: make build-rust
      - name: "Build C Examples"
        run: make build-c
      - name: "Run test"
        run: make test
      - name: "Run test-integration"
        env:
          AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
          AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}
        run: make test
